name: 'Deploy'
description: 'Deploy da Aplicação'

inputs:
  environment:
    description: 'Ambiente do deployment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy da Aplicação
      id: deploy
      shell: bash
      run: |
        echo "Version info:"
        cat build/info.txt
        cat teste.txt
        
        echo "✅ Deploy to ${{ inputs.environment }} completed!"
